dataset:
  name: aptos
  path: dataset
  sub_folder: train_images
  meta_file: df.csv
  meta_columns:
    x: id_code
    y: diagnosis
  image_extention: png
  batch_size: 16
  image_size: 224
  num_classes: 5
  class_activation: 'softmax'
  augment:
    training:
      random_resize_and_crop:
        width: 256
        height: 256
      random_flip: True
    validation: {}

  
model:
  name: efficientnetb0
  weight: imagenet
  task: classification

metrics: cohen_kappa
losses: cohen_kappa

trainer:
  workers: -1
  epochs: 3
  verbosity: 1
  multi_processing: False
  gradient_accumulation: null
  mixed_precision: True
  xla_accelerate: False
  accelerator: gpu
  learning_rate: 0.001
  optimizer: adam

visualization:
  save_images: False
  log_images: False 
  save_path: null 

project:
  seed: 1337
  path: ./results

logging:
  logger: []

